app/Http/routes.php
<?php
use Illuminate\Routing\Router;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/** @var Router $router */
$router = app(Router::class);

$router->get('/', ['uses' => 'HomeController@index', 'as' => 'home']);
$router->get('/casinos', ['uses' => 'HomeController@findCasinos', 'as' => 'casinos']);

$router->auth();

$router->group([
    'namespace' => 'Admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth'],
], function (Router $router) {
    $router->get('/', function() {
        return redirect()->route('admin.casinos.index');
    });

    $router->group([
        'prefix' => 'casinos',
        'as' => 'casinos.',
    ], function (Router $router) {
        $router->get('/', ['uses' => 'Casinos@index', 'as' => 'index']);
        $router->get('/create', ['uses' => 'Casinos@create', 'as' => 'create']);
        $router->post('/create', ['uses' => 'Casinos@store', 'as' => 'create']);
        $router->get('/{id}/edit', ['uses' => 'Casinos@edit', 'as' => 'update']);
        $router->put('/{id}/edit', ['uses' => 'Casinos@update', 'as' => 'update']);
        $router->delete('/{id}/destroy', ['uses' => 'Casinos@destroy', 'as' => 'destroy']);
    });
});

app/Casino.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Casino extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'longitude',
        'latitude',
        'opening_times'
    ];

    /**
     * Finds the casinos nearest to the given longitude and latitude, but returns a subset that is restricted to a
     * specific distance limit
     *
     * @param float $longitude
     * @param float $latitude
     * @param int $distanceLimit The maximum distance in KM that we should return
     *
     * @return Collection
     */
    public function findByNearest(float $longitude, float $latitude, int $distanceLimit = 50)
    {
        $casinos = DB::table('casinos')
            ->selectRaw(
                'id, name, opening_times, longitude, latitude,
                ROUND(ST_Distance_Sphere(POINT(?, ?), Point(longitude, latitude)) / 1000 ) distance',
                [
                    'long' => $longitude,
                    'lat' => $latitude
                ]
            )
            ->having('distance', '<=', $distanceLimit)
            ->orderBy('distance', 'ASC')
            ->get();

        return $casinos;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/Casinos.php
<?php

namespace App\Http\Controllers\Admin;

use App\Casino;
use App\Http\Requests\CasinoRequest;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class Casinos extends Controller
{

    /**
     * Lists all casinos
     *
     * @return View
     */
    public function index()
    {
        $casinos = Casino::paginate(10);

        return view('admin.casinos.index', [
            'casinos' => $casinos
        ]);
    }

    /**
     * Shows the form to create a new Casino
     *
     * @return View
     */
    public function create()
    {
        return view('admin.casinos.new', ['casino' => new Casino]);
    }

    /**
     * Stores a new Casino into the system, then redirects you to the edit page for it
     *
     * @param CasinoRequest $request The validated Request data
     * @return RedirectResponse
     */
    public function store(CasinoRequest $request)
    {
        $casino = Casino::create([
            'name' => $request->get('name'),
            'latitude' => $request->get('latitude'),
            'longitude' => $request->get('longitude'),
            'opening_times' => $request->get('opening_times'),
        ]);

        return redirect()
            ->route('admin.casinos.update', $casino->id)
            ->with('success', 'Casino Successfully Added');
    }

    /**
     * Shows the form to edit a Casino
     *
     * @param int $id The ID of the casino to edit
     * @return View
     */
    public function edit(int $id)
    {
        $casino = Casino::find($id);

        return view('admin.casinos.edit', [
            'casino' => $casino
        ]);
    }

    /**
     * Updates the given casino then redirects you back to the edit page
     *
     * @param CasinoRequest $request The validated casino data
     * @param int $id The ID of the casino to update
     * @return RedirectResponse
     */
    public function update(CasinoRequest $request, int $id)
    {
        $casino = Casino::find($id);

        $casino->name = $request->get('name');
        $casino->latitude = $request->get('latitude');
        $casino->longitude = $request->get('longitude');
        $casino->opening_times = $request->get('opening_times');

        $casino->save();

        return redirect()
            ->route('admin.casinos.update', $casino->id)
            ->with('success', 'Casino Successfully Updated');
    }

    public function destroy(int $id)
    {
        Casino::destroy($id);

        return redirect()
            ->route('admin.casinos.index')
            ->with('success', 'Casino Successfully Deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Casino;
use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    /**
     * Returns the nearest Casinos to the given long and lat, defaults to a 20KM Search
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function findCasinos(Request $request)
    {
        $casinoModel = new Casino();
        $casinos = $casinoModel->findByNearest(
            $request->get('lng'),
            $request->get('lat'),
            $request->get('amount', 20)
        );

        return response()->json($casinos);
    }
}

resources/views/admin/casinos/_form.blade.php
<div class="row">
    <div class="medium-6 columns">
        <div class="row">
            <div class="small-12 columns">
                <label>
                    Casino Name
                    <input type="text" name="name" placeholder="Casino Name" value="{{ old('name', $casino->name) }}">
                </label>
            </div>
        </div>
        <div class="row">
            <div class="small-12 columns">
                <label for="casino-address">Casino Address</label>

                <div class="input-group">
                    <input class="input-group-field" id="casino-address" type="text" placeholder="Casino Address">
                    <div class="input-group-button">
                        <button id="map-search" class="button">Search</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-6 columns">
                <label>
                    Latitude
                    <input name="latitude" id="latitude" type="number" min="-90" max="90" step="any" value="{{ old('latitude', $casino->latitude) }}">
                </label>
            </div>
            <div class="small-6 columns">
                <label>
                    Longitude
                    <input name="longitude" id="longitude" type="number" min="-180" max="180" step="any" value="{{ old('longitude', $casino->longitude) }}">
                </label>
            </div>
        </div>

        <div class="row">
            <div class="small-12 columns">
                <label>
                    Opening Times
                    <textarea name="opening_times" id="opening-times" rows="4">{{ old('opening_times', $casino->opening_times) }}</textarea>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="small-12 columns">
                <div class="button-group expanded">
                    <button type="submit" class="button primary">Save</button>
                    <a href="{{ route('admin.casinos.index') }}" class="button alert">Cancel</a>
                </div>
            </div>
        </div>
    </div>

    <div class="medium-6 columns">
        <div style="height: 100%;" class="map"></div>
    </div>
</div>

resources/views/admin/casinos/_form_scripts.blade.php
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnUYdBMGVjemRuVbLylwREx0CBZQHY330&callback=initMaps"
        type="text/javascript"></script>
<script>
    "use strict";
    var initMaps = function() {
        let geocoder = new google.maps.Geocoder();

        let marker;

        Array.prototype.map.call(document.querySelectorAll('.map'), initMap);

        function searchForCasino(map, geocoder, address) {
            geocoder.geocode({
                address
            }, function (results, status) {
                if (status = google.maps.GeocoderStatus.OK) {
                    let location = results[0].geometry.location;

                    updateLocation({
                        lat: location.lat(),
                        lng: location.lng()
                    }, map);
                } else {
                    console.error(status);
                }
            });
        }

        function updateLocation(location, map) {
            if (!marker) {
                marker = new google.maps.Marker({
                    position: location,
                    map: map,
                    draggable: true
                });
            } else {
                marker.setPosition(location);
            }

            marker.addListener('dragend', function(e) {
                updateLocation({
                    lat: e.latLng.lat(),
                    lng: e.latLng.lng(),
                }, map)
            })

            map.panTo(location);

            document.getElementById('latitude').value = parseFloat(location.lat).toFixed(6);
            document.getElementById('longitude').value = parseFloat(location.lng).toFixed(6);
        }

        function initMap(mapEl) {
            let defaultLocation = {
                lat: Number(document.getElementById('latitude').value || 54.967948),
                lng: Number(document.getElementById('longitude').value || -1.621132)
            }

            let map = new google.maps.Map(mapEl, {
                zoom: 12,
                scrollwheel: false,
                center: defaultLocation
            });

            updateLocation(defaultLocation, map);

            map.addListener('click', function(e) {
                updateLocation({
                    lat: e.latLng.lat(),
                    lng: e.latLng.lng(),
                }, map)
            });

            document.getElementById('map-search').addEventListener('click', function(e) {
                e.preventDefault();
                searchForCasino(map, geocoder, document.getElementById('casino-address').value);
            })
        }
    };
</script>

resources/views/admin/casinos/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Casino')

@section('content')
    <div class="row">
        <div class="small-12 columns">
            <h1>Edit Casino</h1>
        </div>
    </div>

    <form method="post" action="{{ route('admin.casinos.update', $casino->id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}

        @include('admin.casinos._form')
    </form>
@endsection

@section('scripts')
    @include('admin.casinos._form_scripts')
@endsection

resources/views/admin/casinos/index.blade.php
@extends('layouts.admin')

@section('title', 'All Casinos')

@section('content')
    <div class="row">
        <div class="small-12 columns">
            <h1>All Casinos</h1>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            {{ $casinos->links() }}
        </div>
    </div>

    <div class="row">
        @foreach($casinos as $casino)
            <div class="small-12 medium-6 columns">
                <div class="callout">
                    <div class="row">
                        <div class="large-6 columns">
                            <h2>{{ $casino->name }}</h2>

                            <form method="post" action="{{ route('admin.casinos.destroy', $casino->id) }}">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <div class="expanded small button-group">
                                    <a href="{{ route('admin.casinos.update', $casino->id) }}" class="warning button">Edit</a>
                                    <button class="alert button">Delete</button>
                                </div>
                            </form>
                        </div>
                        <div class="columns">
                            <div class="map"
                                 style="min-height: 12rem"
                                 data-latitude="{{ $casino->latitude }}"
                                 data-longitude="{{ $casino->longitude }}"></div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="row">
        <div class="small-12 columns">
            {{ $casinos->links() }}
        </div>
    </div>
@endsection

@section('scripts')
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnUYdBMGVjemRuVbLylwREx0CBZQHY330&callback=initMaps"
            type="text/javascript"></script>
    <script>
        "use strict";
        function initMaps() {
            Array.prototype.map.call(document.querySelectorAll('.map'), initMap);
        }

        function initMap(mapNode) {
            let latLng = {
                lat: Number(mapNode.dataset.latitude),
                lng: Number(mapNode.dataset.longitude)
            };

            let map = new google.maps.Map(mapNode, {
                zoom: 10,
                scrollwheel: false,
                draggable: false,
                center: latLng
            });

            let marker = new google.maps.Marker({
                position: latLng,
                map: map
            });
        }
    </script>
@endsection

resources/views/admin/casinos/new.blade.php
@extends('layouts.admin')

@section('title', 'New Casino')

@section('content')
    <div class="row">
        <div class="small-12 columns">
            <h1>New Casino</h1>
        </div>
    </div>

    <form method="post" action="{{ route('admin.casinos.create') }}">
        {{ csrf_field() }}

        @include('admin.casinos._form')
    </form>
@endsection

@section('scripts')
    @include('admin.casinos._form_scripts')
@endsection

resources/views/admin/dashboard/index.blade.php
@extends('layouts.admin')

@section('title', 'Dashboard')

@section('content')

@endsection

resources/views/admin/flashes.blade.php
@if (session('success'))
    <div class="row">
        <div class="small-12 columns">
            <div class="callout success" data-closable>
                <button type="button" class="close-button" data-dismiss="alert" aria-label="Dismiss Alert" data-close>
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>Awesome!</strong> {{ session('success') }}
            </div>
        </div>
    </div>
@endif

@if (count($errors) > 0)
    <div class="row">
        <div class="small-12 columns">
            <div class="callout alert" data-closable>
                <button type="button" class="close-button" data-dismiss="alert" aria-label="Dismiss Alert" data-close>
                    <span aria-hidden="true">&times;</span>
                </button>

                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

resources/views/admin/nav.blade.php
<div class="top-bar">
    <div class="top-bar-title">
        <strong>Bede Casino</strong>
    </div>
     <div class="top-bar-left">
        <ul class="menu dropdown" data-dropdown-menu>
            <li>
                <a href="#">Casinos</a>
                <ul class="menu vertical">
                    <li><a href="{{ route('admin.casinos.index') }}">List Casinos</a></li>
                    <li><a href="{{ route('admin.casinos.create') }}">Add Casino</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="shrink top-bar-right">
        <ul class="dropdown menu align-right" data-dropdown-menu>
            <li>
                <a href="#">{{ Auth::user()->name }}</a>
                <ul class="menu vertical">
                    <li><a href="{{ url('/logout') }}">Log Out</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Find a Casino')

@section('content')

    <div class="row">
        <div class="small-12 columns">
            <h1>Bede Casino</h1>
        </div>
    </div>

    <div class="row">
        <div class="medium-4 columns">
            <button id="use-current-location" class="button expanded">
                Use Current Location
            </button>

            <form id="search-address">
                <label for="address">
                    Find From Address
                </label>

                <div class="input-group">
                    <input class="input-group-field" id="address" name="address" type="text" placeholder="Address">
                    <div class="input-group-button">
                        <button class="button">Search</button>
                    </div>
                </div>
            </form>

        </div>
        <div class="medium-8 columns">
            <div class="flex-video widescreen map"></div>
        </div>
    </div>

@endsection

@section('scripts')
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnUYdBMGVjemRuVbLylwREx0CBZQHY330&callback=initMap"
            type="text/javascript"></script>

    <script>
        "use strict";

        let currentLocation;

        let markers = [];

        let map;

        let geocoder;

        // If geolocation is available, use it.
        if ('geolocation' in navigator) {
            $('body').on('click', '#use-current-location', function(e) {
                e.preventDefault();

                navigator.geolocation.getCurrentPosition(function(position) {
                    searchLocation(position.coords.latitude, position.coords.longitude);
                }, function() {}, {enableHighAccuracy: true});
            });

        } else {
            $('#use-current-location').remove();
        }

        $('body').on('submit', '#search-address', function(e) {
            e.preventDefault();

            geocodeAddress(document.getElementById('address').value);
        });

        function geocodeAddress(address) {
            if (!geocoder) {
                geocoder = new google.maps.Geocoder;
            }

            geocoder.geocode({
                address
            }, function (results, status) {
                if (status = google.maps.GeocoderStatus.OK) {
                    let location = results[0].geometry.location;

                    searchLocation(location.lat(), location.lng());
                } else {
                    console.error(status);
                }
            });
        }

        function searchLocation(lat, lng) {
            updateLocation({lat, lng}, map);

            $.getJSON('{{ route('casinos') }}', {
                lat: lat,
                lng: lng,
            }).done(dropPins);
        }

        // Map Functions
        function initMap() {
            let mapEl = document.querySelectorAll('.map')[0];
            let defaultLocation = {
                lat: Number(54.967948),
                lng: Number(-1.621132)
            };
            map = new google.maps.Map(mapEl, {
                zoom: 12,
                scrollwheel: false,
                center: defaultLocation
            });

            updateLocation(defaultLocation, map);
        }

        function dropPins(data) {
            markers.forEach(function(marker) {
                marker.setMap(null);
            });

            markers = [];

            data.forEach(function(entry, index) {
                let marker = new google.maps.Marker({
                    map: map,
                    position: {
                        lat: entry.latitude,
                        lng: entry.longitude,
                    },
                    title: entry.name,
                });

                let opening_times = (entry.opening_times || "").replace('\n', '<br>');

                let content = `<strong>${entry.name}</strong>
<div class="opening-times">${opening_times}</div>`;

                let infoWindow = new google.maps.InfoWindow({
                    content
                });

                marker.addListener('click', function() {
                    infoWindow.open(map, marker);
                });

                if (index === 0) {
                    map.panTo(marker.position);
                    infoWindow.open(map, marker);
                }

                markers.push(marker);
            });
        }

        function updateLocation(location, map) {
            map.panTo(location);
        }
    </script>
@endsection

resources/views/layouts/admin.blade.php
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title') - Bede Casino</title>
    <link href="{{ elixir('css/admin.css') }}" rel="stylesheet" type="text/css" media="all">
</head>
<body>

@include('admin.nav')
@include('admin.flashes')

@yield('content')

<script src="{{ elixir('js/admin.js') }}"></script>
@yield('scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title') - Bede Casino</title>
    <link href="{{ elixir('css/app.css') }}" rel="stylesheet" type="text/css" media="all">
</head>
<body>
@yield('content')

<script src="{{ elixir('js/app.js') }}"></script>
@yield('scripts')
</body>
</html>